-- =========================================================
-- Esquema Oracle para Arepas El Poblado
-- Origen: estructura PostgreSQL / Neon
-- Destino: Oracle Autonomous Database
-- =========================================================

-- Nota:
-- Este script crea las tablas principales adaptadas para Oracle.
-- Usa columnas IDENTITY para las llaves primarias numéricas.
-- Los datos se cargarán después desde archivos CSV o inserts.

-- =========================================================
-- TABLAS DE CATÁLOGO
-- =========================================================

CREATE TABLE rol (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE estado_usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_estado_usuario VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE estado_pedido (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_estado_pedido VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE categoria (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE
);

-- =========================================================
-- USUARIOS
-- =========================================================

CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(120) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    telefono VARCHAR2(20) NULL,
    rol_id NUMBER NOT NULL,
    estado_usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_usuarios_rol
        FOREIGN KEY (rol_id) REFERENCES rol(id),
    CONSTRAINT fk_usuarios_estado
        FOREIGN KEY (estado_usuario_id) REFERENCES estado_usuario(id)
);

-- =========================================================
-- PRODUCTOS
-- =========================================================

CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion CLOB NULL,
    precio NUMBER(10,2) NOT NULL,
    stock NUMBER DEFAULT 0,
    imagen VARCHAR2(255) NULL,
    activo NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    imagen_url CLOB NULL,
    categoria_id NUMBER NOT NULL,
    CONSTRAINT fk_productos_categoria
        FOREIGN KEY (categoria_id) REFERENCES categoria(id)
);

-- =========================================================
-- PEDIDOS
-- =========================================================

CREATE TABLE pedidos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    cliente_direccion CLOB NULL,
    total NUMBER(10,2) DEFAULT 0 NOT NULL,
    numero_pedido VARCHAR2(50) UNIQUE,
    fecha_pedido TIMESTAMP NULL,
    fecha_entrega TIMESTAMP NULL,
    notas CLOB NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    estado_pedido_id NUMBER NOT NULL,
    CONSTRAINT fk_pedidos_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_pedidos_estado
        FOREIGN KEY (estado_pedido_id) REFERENCES estado_pedido(id)
);

-- =========================================================
-- DETALLES DEL PEDIDO
-- =========================================================

CREATE TABLE detalles_pedido (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    subtotal NUMBER(10,2) NOT NULL,
    created_at TIMESTAMP NULL,
    CONSTRAINT fk_detalles_pedido_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
    CONSTRAINT fk_detalles_pedido_producto
        FOREIGN KEY (producto_id) REFERENCES productos(id)
);

-- =========================================================
-- CARRITO
-- =========================================================

CREATE TABLE carritos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_carritos_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE carrito_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL,
    cantidad NUMBER DEFAULT 1 NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_carrito_items_carrito
        FOREIGN KEY (carrito_id) REFERENCES carritos(id),
    CONSTRAINT fk_carrito_items_producto
        FOREIGN KEY (producto_id) REFERENCES productos(id),
    CONSTRAINT uq_carrito_producto UNIQUE (carrito_id, producto_id)
);

-- =========================================================
-- ÍNDICES RECOMENDADOS
-- =========================================================

CREATE INDEX idx_usuarios_email ON usuarios(email);
CREATE INDEX idx_pedidos_usuario_id ON pedidos(usuario_id);
CREATE INDEX idx_pedidos_numero ON pedidos(numero_pedido);
CREATE INDEX idx_detalles_pedido_pedido_id ON detalles_pedido(pedido_id);
CREATE INDEX idx_detalles_pedido_producto_id ON detalles_pedido(producto_id);
CREATE INDEX idx_carrito_items_carrito_id ON carrito_items(carrito_id);
CREATE INDEX idx_carrito_items_producto_id ON carrito_items(producto_id);

-- =========================================================
-- DATOS BÁSICOS INICIALES
-- =========================================================

INSERT INTO rol (id, nombre_rol) VALUES (1, 'admin');
INSERT INTO rol (id, nombre_rol) VALUES (2, 'cliente');

INSERT INTO estado_usuario (id, nombre_estado_usuario) VALUES (1, 'activo');
INSERT INTO estado_usuario (id, nombre_estado_usuario) VALUES (2, 'inactivo');
INSERT INTO estado_usuario (id, nombre_estado_usuario) VALUES (3, 'bloqueado');

INSERT INTO estado_pedido (id, nombre_estado_pedido) VALUES (1, 'pendiente');
INSERT INTO estado_pedido (id, nombre_estado_pedido) VALUES (2, 'en proceso');
INSERT INTO estado_pedido (id, nombre_estado_pedido) VALUES (3, 'pagado');
INSERT INTO estado_pedido (id, nombre_estado_pedido) VALUES (4, 'cancelado');
INSERT INTO estado_pedido (id, nombre_estado_pedido) VALUES (5, 'completado');

COMMIT;
